columnSuffix: null
handle: applyUrl
instructions: null
name: 'Apply URL'
searchable: true
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
