defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 933be93b-2da3-40ef-bb28-2f375b82685b # Imported Vacancy
handle: importedVacancies
maxAuthors: 1
name: 'Imported Vacancies'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  b2c33b48-5602-41ab-acef-041c4a31e169: # cosmowebapp
    enabledByDefault: false
    hasUrls: true
    template: vacancies/_entry
    uriFormat: 'vacancies/{slug}'
type: channel
